### ISSUE TITLE
FR7. Ducki must screen users and tailor questions to create a more dynamic and personalized experience

### ISSUE THREAD

**Issue by jaherndz** [UNO-CSCI4830/Ducki#15]
### FR2. Display Chat Log
- **Goal:** Have Ducki be able to tailor questions for each user to make it more dynamic experience
- **Stakeholders:** All
- **Description:** The user should be able to display past chat logs between them and the Ducki bot.
- **Origin:** Ducki should be able to process answers from a questionnaire about the user and change how it answers questions depending on the answers. 
- **Version:** 1.0
- **Date:** 09/14/2024
- **Priority:** 2

**Comment by lukeirwin03** [comment]
We have changed scope a little bit an will no longer be implementing this feature as we have decided to go another direction to have a more conversational approach.
