### ISSUE TITLE
FR10. Containerization for Easy Use

### ISSUE THREAD

**Issue by jaherndz** [UNO-CSCI4830/Ducki#18]
### FR10. Containerization for Easy Use
- **Goal:** Goal: Ducki must be containerized for easy deployment.
- **Stakeholders:** Open-source developers
- **Description:** Ducki will be distributed using Docker to enable for a seamless setup and easy development. This is to minimize the number of things a user must do to get Ducki set-up and running.
- **Origin:** Discussions on customizability
- **Version:** 1.0
- **Date:** 09/30/2024
- **Priority:** 1

**Comment by lukeirwin03** [comment]
Ducki has been containerized and is ready for deployment using Docker.
