### ISSUE TITLE
NFR2. Run locally with minimal dependencies

### ISSUE THREAD

**Issue by SoraKitti** [UNO-CSCI4830/Ducki#20]
### NFR2. Ducki must run locally with minimal dependencies
- **Goal:** Ducki should run seamlessly on local machines, minimizing the need for extensive installations or configurations.
- **Stakeholders:** All
- **Description:** By using Docker, Ducki will be packaged to ensure a streamlined setup, requiring users to install only essential dependencies, reducing overhead and complexity.
- **Origin:** Based on the initial project specification document, team members came up with this description during the first meeting.
- **Version:** 1.0
- **Date:** 09/14/2024
- **Priority:** 1

**Comment by lukeirwin03** [comment]
Through containerizing the application, we were able to limit the dependencies for the local user to just Docker Desktop. Though we do need to make sure that the versions of the packages are maintained.
