### ISSUE TITLE
NFR3. Free to use with Affordable API Integration

### ISSUE THREAD

**Issue by SoraKitti** [UNO-CSCI4830/Ducki#21]
### NFR3. Ducki must remain free with affordable API integration
- **Goal:** Ducki will be a free application, with optional API integration for additional functionality, ensuring accessibility to all users.
- **Stakeholders:** All
- **Description:** Ducki itself will be free, and any APIs used for extended features will be chosen to minimize costs to users, ensuring that students and hobbyists can affordably access enhanced capabilities.
- **Origin:** Based on the initial project specification document, team members came up with this description during the first meeting.
- **Version:** 1.0
- **Date:** 09/14/2024
- **Priority:** 1

**Comment by lukeirwin03** [comment]
Ducki will remain open-source and free for anyone to use. The only requirement is that the user has a valid OpenAI API key and Docker installed.
