### ISSUE TITLE
NFR4. Clear Installation Instructions

### ISSUE THREAD

**Issue by SoraKitti** [UNO-CSCI4830/Ducki#22]
### NFR4. Ducki must include clear installation instructions for users to easily set up the application.
- **Goal:** Ducki’s GitHub repository will include detailed, easy-to-follow installation instructions to ensure all users can quickly set up the application.
- **Stakeholders:** All
- **Description:** The installation guide will be simple, with clear steps and troubleshooting tips, allowing users of varying technical backgrounds to install and configure Ducki without issues. Ducki will also walk the user through the setup process once they have started the app.
- **Origin:** Based on the initial project specification document, team members came up with this description during the first meeting.
- **Version:** 1.0
- **Date:** 09/14/2024
- **Priority:** 1

**Comment by lukeirwin03** [comment]
In the repository README.md there are clear instructions for how to install and setup Ducki.
